# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cpm < Formula
  desc "NEO Blockchain Contract Package Manager"
  homepage "https://github.com/CityOfZion/cpm"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CityOfZion/cpm/releases/download/v0.2.0/cpm_0.2.0_darwin_amd64"
      sha256 "a3d10987f01fe1981faa0edf83d75a463f76896716eb1db54a00d26be43b9aea"

      def install
        bin.install "cpm_0.2.0_darwin_amd64" => "cpm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CityOfZion/cpm/releases/download/v0.2.0/cpm_0.2.0_darwin_arm64"
      sha256 "1ff29a5ad98566668f745de5bba0c01e52e49c352a64dad65ac0d6cb0d542d40"

      def install
        bin.install "cpm_0.2.0_darwin_arm64" => "cpm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/CityOfZion/cpm/releases/download/v0.2.0/cpm_0.2.0_linux_amd64"
      sha256 "f2d167b86061a6639cf70d5bea0001c2ce1a6d18cdf53a0b79a50e3f123df5e7"

      def install
        bin.install "cpm_0.2.0_linux_amd64" => "cpm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CityOfZion/cpm/releases/download/v0.2.0/cpm_0.2.0_linux_arm64"
      sha256 "12e9b95f825308bbc526fff2b03a9c86db6fe2e93d1d7e50cbf87ca025b01d43"

      def install
        bin.install "cpm_0.2.0_linux_arm64" => "cpm"
      end
    end
  end
end
