# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cpm < Formula
  desc "NEO Blockchain Contract Package Manager"
  homepage "https://github.com/CityOfZion/cpm"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/CityOfZion/cpm/releases/download/v1.0.0/cpm_1.0.0_darwin_arm64.tar.gz"
      sha256 "27ffb86626828e51193c793fe62a92acfcc9f2bc099eecf6df1054720530b8ad"

      def install
        bin.install "cpm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/CityOfZion/cpm/releases/download/v1.0.0/cpm_1.0.0_darwin_amd64.tar.gz"
      sha256 "7b4868e971f022b282bba10772c197a49fff6cc74ca4c874fbe05a17457b37c8"

      def install
        bin.install "cpm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CityOfZion/cpm/releases/download/v1.0.0/cpm_1.0.0_linux_arm64.tar.gz"
      sha256 "55b3d8991f13a58f41f2330085184578da172c7ce6889b0864c56cf17b5b92cb"

      def install
        bin.install "cpm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/CityOfZion/cpm/releases/download/v1.0.0/cpm_1.0.0_linux_amd64.tar.gz"
      sha256 "9f51b0c9e07f05d59842536d4adba6687288905c4c8fb0849e15753cdf353ca6"

      def install
        bin.install "cpm"
      end
    end
  end
end
