# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cpm < Formula
  desc "NEO Blockchain Contract Package Manager"
  homepage "https://github.com/CityOfZion/cpm"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/CityOfZion/cpm/releases/download/v0.6.0/cpm_0.6.0_darwin_arm64"
      sha256 "5c6bbb4a22e1d53d7f7016ec248e9ac1e9b0bae024c298cfa367880ef9fa5edc"

      def install
        bin.install "cpm_0.6.0_darwin_arm64" => "cpm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/CityOfZion/cpm/releases/download/v0.6.0/cpm_0.6.0_darwin_amd64"
      sha256 "1d64f07ce084d430889fd376f9165a55cfae1970e011619334a7ed1cef8af742"

      def install
        bin.install "cpm_0.6.0_darwin_amd64" => "cpm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/CityOfZion/cpm/releases/download/v0.6.0/cpm_0.6.0_linux_amd64"
      sha256 "eb88083a42e421702e265968e6e3544941beb302faba993b8a1ae0d68803bee7"

      def install
        bin.install "cpm_0.6.0_linux_amd64" => "cpm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CityOfZion/cpm/releases/download/v0.6.0/cpm_0.6.0_linux_arm64"
      sha256 "5d8ff8f89ca09dcb67312760e3a3810abec0dbcd5bce979acd12570b05e03ef3"

      def install
        bin.install "cpm_0.6.0_linux_arm64" => "cpm"
      end
    end
  end
end
