# This file was generated by GoReleaser. DO NOT EDIT.
cask "cpm" do
  version "1.1.3"

  on_macos do
    on_intel do
      sha256 "47396778f7e40d4089be514ac22164283a61951fd2c6a1acfea591ea75121b46"
      url "https://github.com/CityOfZion/cpm/releases/download/v#{version}/cpm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "178301aa1b3acbdaed85350537e62d56fea3425b4257a87eb9c905fa8466a333"
      url "https://github.com/CityOfZion/cpm/releases/download/v#{version}/cpm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9987a2ca376f4937f839dfc271a7c4bc16424d51c584224634bcf33a3ec9a145"
      url "https://github.com/CityOfZion/cpm/releases/download/v#{version}/cpm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4bc46090c47c073f3285431405d004bc06418e9e63af59983a2d13f905f146a7"
      url "https://github.com/CityOfZion/cpm/releases/download/v#{version}/cpm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cpm"
  desc "NEO Blockchain Contract Package Manager"
  homepage "https://github.com/CityOfZion/cpm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cpm"

  # No zap stanza required

end
