# This file was generated by GoReleaser. DO NOT EDIT.
cask "cpm" do
  version "1.1.4"

  on_macos do
    on_arm do
      sha256 "e1cab010b51401feff6379a39523083df5a4d48b1cf6629acd4dabeeb3a23dc6"
      url "https://github.com/CityOfZion/cpm/releases/download/v#{version}/cpm_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "24f61579edbeea180da5505c4997ad066388feeb14bf191042ec75cadba8caac"
      url "https://github.com/CityOfZion/cpm/releases/download/v#{version}/cpm_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aa4f92fc80f0f11913ecf6dad8778621bcd5a03d8500e9b67310cd30be7efad9"
      url "https://github.com/CityOfZion/cpm/releases/download/v#{version}/cpm_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2541b2770498dc070247137aff5e54cc1d305905063536028d6a398e1c2af07c"
      url "https://github.com/CityOfZion/cpm/releases/download/v#{version}/cpm_#{version}_linux_amd64.tar.gz"
    end
  end

  name "cpm"
  desc "NEO Blockchain Contract Package Manager"
  homepage "https://github.com/CityOfZion/cpm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cpm"

  # No zap stanza required
end
